/// Flutter icons CustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData android = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angular = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kotlin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solidity = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
